author: eccentric_nz
description: Be a like a gunslinging cowboy and be the quickest on the draw.
main: me.eccentric_nz.plugins.quickdraw.Quickdraw
name: QuickDraw
startup: postworld
dev-url: http://dev.bukkit.org/server-mods/quickdraw/
version: '1.0'
depend: [Vault]
permissions:
  quickdraw.draw:
    default: op
    description: Allow players to participate in QuickDraw challenges.
commands:
  quickdraw:
    aliases: [qd]
    permissions: quickdraw.draw
    description: View the QuickDraw best times.
    usage: /<command> [me|all]